### ISSUE TITLE
Tomcat 9

### ISSUE THREAD

**Issue by Hugolarson** [vaadin/base-starter-gradle#151]
Hi,

Should it not run with tomcat 9? Why is 10 required?

dependency  javax.servlet:javax.servlet-api:3.1.0 is supported even on tomcat 8.5

Thanks,

**Comment by mcollovati** [comment]
Vaadin 24 is based on Jakarta EE 10, that involved the migration from `javax.*` to `jakarta.*` packages.
The first version of Tomcat supporting JEE 10 is Tomcat 10.1.

**Comment by Hugolarson** [comment]
Hi,

In build gradle there is:
providedCompile "javax.servlet:javax.servlet-api:3.1.0"

Should this not be changed to jakarta?
