### ISSUE TITLE
Confusing comment in build.gradle

### ISSUE THREAD

**Issue by mr1chter** [vaadin/base-starter-gradle#65]
This snippet says that it can be omitted and is just there for showing how to configure the vaadin plugin:

https://github.com/vaadin/base-starter-gradle/blob/04160c00c964f45eedaff85d663791f2cd62d5ea/build.gradle#L28-L33

But the [documentation](https://vaadin.com/docs/latest/flow/guide/start/gradle#all-options) says that `pnpmEnable` defaults to true.

What is right here?

**Comment by caalador** [comment]
The documentation is wrong in this respect and should be updated.
The default was changed to npm from pnpm for Vaadin 23 so for 23+ documentation it should say false, but for others the documentation and code should say true.

**Comment by mr1chter** [comment]
Thanks for the clarification!
